funfact/lang/_ast.py, funfact/lang/_semiring.py, funfact/lang/_tensor.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_syntax_validation.py, funfact/model/_factorization.py, funfact/util/iterable.py, funfact/util/set.py
Summary:
- Added the `>>` operator for the explicit specification of output tensor indices.
- A shorthand syntax, which introduces the `~` modifier to individual indices, will be implemented in #17.
- Replaces #16.
- Closes #6.
Example:
```
A = ff.tensor('A', 2, 3)
B = ff.tensor('B', 3, 4)
tsrex = A[i, j] * B[j, k] >> (k, j)
```
give rise to the following tensor expression
```
>>
├── *
│   ├── A[i,j]
│   │   ├── A
│   │   ╰── i,j
│   │       ├── i
│   │       ╰── j
│   ╰── B[j,k]
│       ├── B
│       ╰── j,k
│           ├── j
│           ╰── k
╰── k,j
├── k
╰── j
```
which in addition to carrying out the inner product, also transposes the final result.
This is currently a **work-in-progress**: a forward-backward interpreter is needed to implement index …
=> Added the `>>` syntax for specifying output indices.

funfact/lang/_tensor.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_syntax_validation.py, funfact/lang/test_tensor.py, funfact/model/_factorization.py, funfact/rbf/_base.py, funfact/rbf/_dense_stochgrad.py
Closes #4.
- Introduced a base class `Identifiable`, which both indices and tensors inherit from. Equality checks between identifiable are performed using UUIDs. The human-readable symbols are now purely for the purpose of visualization and TeX rendering.
- Anonymous indices will be automated assigned a readable symbol in the form of `#_{id}`.
- Anonymous tensors will be automated assigned a readable symbol in the form of `λ_{id}`.
Enabling the following usages:
```python
T = ff.tensor(3, 3, 3)
u1 = ff.tensor(10, 3)
u2 = ff.tensor(20, 3)
u3 = ff.tensor(30, 3)
i1, i2, i3, k1, k2, k3 = ff.indices(6)
tsrex = T[k1, k2, k3] * u1[i1, k1] * u2[i2, k2] * u3[i3, k3]
tsrex
```
which returns:
```math
{\\boldsymbol{\\lambda}^{(0)}}_{{{\\#}_{3}}{{\\#}_{4}}{{\\#}_{5}}} \\times …
```
=> Create tensors and indices without explicitly specifying a name

funfact/lang/_tsrex.py
In addition to the default ASCII tree representation, additional fields can be passed as arguments like:
```python
A = ff.tensor('A', 2, 3)
B = ff.tensor('B', 3, 4)
tsrex = A[i, ~j] * B[~j, k]
fac = Factorization(tsrex)
fac.tsrex.asciitree('einspec', 'live_indices', 'data')
```
which returns
```
sum:mul (einspec: ab,bc->abc) (live_indices: [AbstractIndex(Symbol(letter='i', number=None)), AbstractIndex(Symbol(letter='j', number=None)), AbstractIndex(Symbol(letter='k', number=None))]) (data: None)
├── A[i,~j] (einspec: None) (live_indices: [AbstractIndex(Symbol(letter='i', number=None)), AbstractIndex(Symbol(letter='j', number=None))]) (data: None)
│   ├── A (einspec: None) (live_indices: []) (data: [[ 1.1685833   0.3123754  -0.5711    ]
[ 0.13668993 …
```
=> Allow the printout of additional fields in TsrEx asciitree representation.

funfact/lang/_tsrex.py, funfact/lang/interpreter/__init__.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_index_propagation.py
Allows the indices associated with the surviving dimensions to be replaced by new indices.
This is a necessary mechanism to implement #15.
```python
u = ff.tensor(2, 3)
v = ff.tensor(3, 5)
w = ff.tensor(5, 8)
X = ff.tensor(2, 8)
i, j, k, l = ff.indices(4)
a, b, c = ff.indices('a, b, c')
```
```
u[i, j] * v[j, ~k]
```
```
(u[i, j] * v[j, ~k])[a, b]
```
```
(u[i, j] * v[~j, k])[a, b, c]
```
=> Index renaming

funfact/lang/_ast.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_syntax_validation.py
Note: this is only the 'front end' of the Kronecker product syntax. Changed are needed in the evaluator/einop back end to carry out the calculations.
If the same index shows up between a pair of contracting tensors **and** at least one of the occurrences is decorated with the unary index multiplication sign `*`, the a Kronecker-style outer op operation will happen along the associated dimensions.
Example (note the double bracket `[[]]`, which is required in this case since we are _abusing_ the iterable unpacking operator here):
```
A = ff.tensor('A', 4, 4)
B = ff.tensor('B', 3, 4)
i, j = ff.indices('i, j')
A[[*i, j]] * B[i, ~j]
```
Leads to:
```
sum:mul 
├── A[*i,j] 
│   ├── A 
│   ╰── *i,j 
│       ├── *i 
│       ╰── j 
╰── B[i,~j] 
├── B 
╰── i,~j 
├── i 
╰── ~j 
```
and
This should …
=> Use the `[[*i, ...]]` syntax to denote Kronecker product indices.

funfact/lang/_ast.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/test_tsrex.py
Every tensor expression now has the `.T` property, which when indexed indicate the transposition to be applied to the source tensor.
Example:
```python
A = ff.tensor('A', 2, 3)
fac = Factorization(A[i, j].T[j, i])
print(fac())
print(fac['A'])  # fac() is the transposition o f A
```
and
```python
A = ff.tensor('A', 2, 3, 4)
fac = Factorization(A[i, j, k].T[k, i, j])
print(fac())
print(fac['A'])  # reorder dimensions of A
```
All three syntaxes concerns the manipulation of indices of the tensor expression output. However:
- The `>>` syntax is only applied to a binary operation and is used to facilitate surviving index inference. It specifies which indices from the lhs/src tensors should be preserved.
- The direct `[..]` is only meant to **rename** the remaining dimensions of a (potentially …
=> Transposition for all tensor expressions.

funfact/lang/__init__.py
Takes care of the issue that Google Colab does not render TeX in cell outputs (not the text cells) by default.
=> Enable MathJAX rendering explicitly

funfact/lang/_tsrex.py, funfact/lang/interpreter/__init__.py, funfact/lang/interpreter/_shape.py, funfact/model/_factorization.py
Closes #31.
Example usage:
```
A = ff.tensor('A', 2, 3, 4)
B = ff.tensor('B', 4, 3, 5)
i, j, k, l = ff.indices('i, j, k, l')
tsrex = A[i, j, k] * B[k, ~j, l]
f = Factorization(tsrex)
print(f.shape)
print(tsrex.shape)
print(tsrex.ndim)
print(tsrex.live_indices)
print(tsrex.einspec)
```
=> Shape analyzer and exposing properties of tensor expressions

funfact/lang/_tsrex.py, funfact/model/_factorization.py
Solves #43 
Removed `__init__` from `_BaseEx` and replaced with `lru_cache` decorator.
Code snippet to test timings of repeatedly getting a cached property:
```
T = ff.tensor('T', 3, 3, 3)
u1 = ff.tensor('u_1', 10, 3)
u2 = ff.tensor('u_2', 20, 3)
u3 = ff.tensor('u_3', 30, 3)
i1, i2, i3, k1, k2, k3 = ff.indices('i_1, i_2, i_3, k_1, k_2, k_3')
tsrex = T[k1, k2, k3] * u1[i1, k1] * u2[i2, k2] * u3[i3, k3]
from functools import wraps
from time import time
def timing(f):
@wraps(f)
def wrap(*args, **kw):
ts = time()
result = f(*args, **kw)
te = time()
print('func:%r args:[%r, %r] took: %2.4f sec' %
(f.__name__, args, kw, te-ts))
return result
return wrap
@timing
def time_attribute(tsrex, prop):
return getattr(tsrex, prop)
time_attribute(tsrex,'shape') …
```
=> Caching for tensor expression properties

funfact/util/iterable.py
Fixes #47.
Only unpacks the incoming key if it is explicitly a `List` or `Tuple`, and do not unpack merely because it has an `__iter__` method.
=> Use stricter criterion to avoid confusing true iterables with `*i`.

funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_shape.py, funfact/model/test_factorization.py
Working on Kronecker backend #34. 
There are a few outstanding issues for this draft PR, but the basic functionality works.
**Issues:**
- `_einop` still uses a spec string for now, everything after the identifier `|` at the end of the spec string is considered a Kronecker index
- there is an issue with the `implied_survival` indices: the order between `keep_bound` and `keep_kron` is arbitrary and can be incorrect. See second test case below.
- the shape analyzer is not yet updated
The code snippet below tests the functionality:
```Python
from funfact.lang.interpreter import EinsteinSpecGenerator, IndexPropagator, Evaluator, LeafInitializer
_my_ein = EinsteinSpecGenerator()
_my_index = IndexPropagator()
_my_eval = Evaluator()
_my_init = LeafInitializer()
A = …
```
=> Kronecker backend

funfact/lang/interpreter/_shape.py, funfact/lang/test_tsrex.py
Closes #52. The shape analyzer now throws a `SyntaxError` on the example from the bug report. Simple test cases are added.
=> fixes shape analyzer bug #52

funfact/lang/_math.py
Instead of implementing `conj` as a property of a tensor expression, I decided to make it a math function alongside others like `sin`, `cos`, etc. This is the minimal effort solution for the time being and should be as convenient as the `.conj` property.
Another reason for not doing a property is due to the unresolved discussion in #60.
=> Added the complex conjugate math function. Closes #56.

funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_latex.py, funfact/lang/test_tsrex.py
Closes #60. This avoids the confusion that may arise as discussed in the issue.
=> Use `>>` instead of `.T` to denote transposition.

funfact/lang/_tsrex.py, funfact/util/typing.py
Since a zeroth-order tensor, i.e. a scalar, is one that does not carry any indices, it should be semantically straightforward to allow a zeroth-order tensor to be defined as one whose shape is empty (not even as `[1]`!) and which can be indexed by `[None]` (since there _is_ no indices for it). It turns out the rest of FunFact already works with zeroth-order tensors out of the box.
Example
```
a = ff.tensor('a')
b = ff.tensor()
print(a.ndim)  # expects 0
print(a.shape)  # expects (,)
print(b.live_indices)  # expects []
fac = Factorization(a[[]])
print(fac())  # obtains a single-element vector
vfac = Factorization(b[None], nvec=4)
print(vfac())  # obtains a 4-element vector
```
=> Allow definition of zeroth-order tensors, i.e. scalars. Closes #69.

funfact/__init__.py, funfact/algorithm.py, funfact/backend/_jax.py, funfact/lang/interpreter/_einop.py, funfact/loss.py, funfact/model/_factorization.py, funfact/optim.py
Implements #70 and towards #55
The `factorize` function now works with a vectorized approach. It can give three types of outputs:
- `stop_by='best'`: returns a single (unvectorized) factorization model that has the best fit
- `stop_by=int`: returns a list of unvectorized factorization models that have the `stop_by` (<=nvec) best fits
- 'stop_by='steps' : returns a vectorized factorization model containing the `nvec` best approximations
=> bugfixes + working on factorize

docs/api/index.md, docs/api/indices.md, docs/tsrex.md, funfact/lang/_terminal.py, funfact/lang/_tsrex.py, funfact/lang/test_terminal.py, mkdocs.yml
This PR provides furnished docstrings for the public APIs of the ~~`funfact.lang._terminal`~~ `funfact.lang._tsrex` module, and also added enough tests to achieve 99% coverage ratio for `funfact.lang._terminal`.
correction
=> Documentation + unit tests for `funfact.lang._terminal`

funfact/backend/test_backend.py, requirements.txt, setup.py
Added the `[jax]` and `[torch]` installation targets.
Examples:
``` bash
pip install funfact  # numpy only
pip install funfact[jax]  # installs JAX
pip install funfact[torch]  # installs PyTorch
```
=> Add pytorch to project dependency

docs/installation.md
Updated the `installation.md` documentation for issue #103.
However, the commands like `pip install "funfact[jax]"` do not yet work (at least for me). Let me know what you think @yhtang
=> More information about installation instructions

funfact/algorithm.py, funfact/backend/_jax.py, funfact/backend/_torch.py, funfact/lang/interpreter/_einop.py, funfact/loss.py
This fixes #76, I haven't checked the performance of the  `reshape(..., order='F')` implementation.
The `torch.sum` method is overridden to have the same behavior as `numpy` if axis is an empty tuple. The same will have to be don for other reduction operations: `torch.prod`, `torch.max`, `torch.min`, ...
=> Full functionality for using the PyTorch backend. Fixes #76. Fixes #98.

funfact/backend/_numpy.py, funfact/loss.py
The NumPy backend will now throw an informative error when `factorize` is used:
```
TypeError: NumPy backend does not support autograd and backward mode; use JAX or PyTorch backend instead.
```
All methods from the other two backends have been added to the NumPy backend as well.
=> Numpy autograd error

funfact/algorithm.py, funfact/lang/_terminal.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_vectorize.py, funfact/test_vectorization.py, funfact/vectorization.py
Uses the `broadcast_to` method from the backend to simplify the vectorization of tensor expressions. This does not change any API or frontend behavior.
Also added unit tests to cover all lines in `vectorization.py`.
=> Rewrite vectorizer using `broadcast_to`.

funfact/lang/_ast.py, funfact/lang/_predefined_literal.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_shape.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_syntax_validation.py, funfact/lang/interpreter/_vectorize.py, funfact/lang/test_ast.py, funfact/lang/test_tsrex.py, funfact/test_vectorization.py, setup.py
This PR enables mixed tensor algebra expressions. Essentially, it makes our tensor expression programming model a **superset** of what NumPy implements.
``` py
a = ff.tensor('a', 2, 4)
b = ff.tensor('b', 2, 4)
c = ff.tensor('c', 4, 10)
tsrex = a[i, j] * b[k, j]  # OK, Einstein notation, implied inner product, a @ b.T
tsrex = a * b  # OK, NumPy-style elemtwise operations
tsrex = a @ b.T  # OK, NumPy-style dot product
tsrex = (a + b)[i, j] * c[j, k]  # OK, first computes elementwise add between a and b, and then dot product with c
tsrex = b.T @ (a[i, j] * c[j, k])  # Will be OK after `@` implemented in the next PR.
```
=> Allow hybrid indexed/indexless tensor arithmetics

funfact/__init__.py, funfact/lang/__init__.py, funfact/lang/_ast.py, funfact/lang/_predefined_literal.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_shape.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_syntax_validation.py, funfact/lang/interpreter/_vectorize.py
Also fixes a bug that unnecessarily excludes tensors of broadcastable shapes to act on each other in binary operations.
``` py
a = ff.tensor('a', 2, 3)
b = ff.tensor('b', 2, 3)
fac = ff.Factorization.from_tsrex(a**b)
print(fac())
print(fac.tsrex.asciitree)
fac.tsrex
```
Output:
```
[[      nan 0.6022982 1.4585489]
[      nan       nan       nan]]
binary: float_power 
├── tensor: a 
╰── tensor: b 
```
=> Make exponentiation a special case of binary operations.

funfact/algorithm.py, funfact/backend/__init__.py, funfact/backend/_jax.py, funfact/backend/_meta.py, funfact/backend/_torch.py, funfact/lang/interpreter/_initialization.py, funfact/loss.py, funfact/model/_factorization.py
Bugfix for #84.
Example code for complex optimization:
```python
import numpy as np
ff.use('torch')
m = np.random.rand(4,2,2)
m = m[..., 0] + 1j * m[..., 1]
n = np.random.rand(2,3,2)
n = n[..., 0] + 1j * n[..., 1]
target = m @ n
a = ff.tensor(4,2)
b = ff.tensor(2,3)
i,j,k = ff.indices(3)
tsrex = a[i,j] * b[j,k]
fac = ff.factorize(tsrex, target, nvec=64, max_steps=10000, dtype='target')
```
=> Support for dtype

funfact/backend/_jax.py
JAX returns the complex conjugate of the gradient by default. This PR fixes the JAX backend to return the true complex gradient.
=> conjugate(grad) for JAX

docs/api/initializers.md, funfact/__init__.py, funfact/backend/_jax.py, funfact/backend/_numpy.py, funfact/backend/_torch.py, funfact/backend/test_backend.py, funfact/initializers.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/test_einop.py, funfact/test_initializers.py, mkdocs.yml
Implemented a number of common initialization distributions in `funfact.initializers`.
Each initializer can be either used as-is, or with arguments to tweak the actual distribution being used.
Example usage:
``` py
n, m = img.shape
u = ff.tensor('u', n, r, initializer=ff.initializers.Normal)  # use as-is
v = ff.tensor('v', m, r, initializer=ff.initializers.Normal(dtype=ab.float64))  # override data type
a = ff.tensor('a', r, initializer=ff.initializers.VarianceScaling(np.var(img), axis=0))  # additional config
b = ff.tensor('b')
rbfex = ff.exp(-(u[i, ~k] - v[j, ~k])**2) * a[k] + b[[]]
rbfex
```
=> Initializers

funfact/lang/_ast.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_vectorize.py, funfact/vectorization.py
AChained indexless operations can be correctly vectorized now.
``` py
A = ff.eye(2)
B = ff.tensor(2, 2)
C = ff.eye(2)
tsrex = A & B & C
tsrex_vec = vectorize(tsrex, 4, append=True)
```
~~However, a backend bug popped up after the frontend is fixed. See #136 for details.~~
Also fixes #136, which is due to a bug in the index analyzer.
=> Change vectorizer rewriting rule. Fixes #135. Fixes #136.

.github/workflows/ci.yml, funfact/backend/_torch.py, funfact/initializers.py, tox.ini
With the new Tox/CI config, we can specify the backend used in unit testing and CI runs.
Example usage:
``` bash
tox -e py38-jax
tox -e py39-torch
...
```
=> Use matrix strategy to test both PyTorch and JAX backends during CI

funfact/algorithm.py, funfact/backend/_jax.py, funfact/backend/_torch.py, funfact/lang/interpreter/_vectorize.py, funfact/loss.py, funfact/vectorization.py
This adds complete support for prepending vectorization to:
- FF loss functions
- vectorization.view 
- factorize
- backends
The following code now works correctly:
```python
A = ff.tensor('A', 3, 2)
B = ff.tensor('B', 2, 3)
#tsrex = A[[*i, *j]] * B[[i, j]]
tsrex = A[[i, j]] * B[[j, k]]
target = ff.Factorization.from_tsrex(tsrex)
target = target()
fac = ff.factorize(tsrex, target, nvec=4, append=False)
fac()
```
=> full support for prepend vectorization

funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/test_initialization.py
@campsd discovered the problem:
``` py
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([-1.0, 4.0])
a = ff.tensor('a', a, optimizable=False)
b = ff.tensor('b', b, optimizable=True, prefer=ff.conditions.NonNegative())
i, j = ff.indices('i, j')
tsrex = a[i] * b[j]
fac = ff.Factorization.from_tsrex(tsrex)
```
which leads to `b` being a tensor of length 6. This is because of an incorrect usage of the `broadcast_to/tile` method.
=> Fix bug when populating tensors from concrete initializers

funfact/lang/interpreter/_base.py, funfact/lang/interpreter/test_base.py
Note that it does not achieve complete coverage of all the code lines, because of the abstract nature of the many methods. These however will be covered by subsequent tests for the concrete interpreters.
=> Unit tests for the interpreter base classes.

funfact/lang/interpreter/_einop.py
Despite what the branch name suggests, I ended up still using the `None/Slice(None)` trick to expand the dimensionality of operand tensors. However, this PR achieves two things:
1. Via a different ordering of the indices, we only need to transpose the lhs/rhs tensors. There is no need to transpose the result tensors anymore.
2. This streamlines the transpose-pairwise-reduce-reshape call and paves the way to solve #179.
=> Refactored einop. Closes #109

funfact/lang/_tsrex.py, funfact/lang/interpreter/__init__.py, funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/_einop_compiler.py, funfact/lang/interpreter/_elementwise.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_type_deduction.py, funfact/lang/interpreter/test_einop.py, funfact/model/_factorization.py, funfact/vectorization.py
Implements the mechanism as suggested in #182.
=> Precompile einop specifications using live indices. Fixes #182.

funfact/__init__.py, funfact/generators.py, funfact/lang/_ast.py, funfact/lang/_terminal.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einop_compiler.py, funfact/lang/interpreter/_elementwise.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_indexness.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_type_deduction.py, funfact/lang/interpreter/_vectorize.py, funfact/model/_factorization.py, funfact/parametrized.py
This PR adds a framework to add parametrized tensors to FunFact and closes #220 upon completion. An example implementation for parametrized Givens rotations is provided.
Example usage to compute a Givens QR factorization of a 2 x 2 matrix:
```py
G = ff.parametrized.planar_rotation(0, 1, 2)
R = ff.tensor('R', 2, 2, prefer=ff.conditions.UpperTriangular())
tsrex = G @ R
target = np.array([[1.0, 2.0], [3.0, 4.0]])
fac = ff.factorize(tsrex, target, vec_size=8)
fac()
```
There is an outstanding issue with the generation of the rotation matrices with the JAX backend that is related to the immutability property of `DeviceArray`s we encountered before. The commented out code in `funfact.parametrized.givens_rotation` uses the idea from: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_i …
=> Parametrized Tensors

funfact/backend/_torch.py, funfact/lang/_tsrex.py
Turns out the `torch.float_power` has the following admonition...:
> This function always computes in **double precision**, unlike [torch.pow()](https://pytorch.org/docs/stable/generated/torch.pow.html#torch.pow), which implements more typical [type promotion](https://pytorch.org/docs/stable/tensor_attributes.html#type-promotion-doc). This is useful when the computation needs to be performed in a wider or more precise dtype, or the results of the computation may contain fractional values not representable in the input dtypes, like when an integer base is raised to a negative integer exponent.
=> Eliminate unnecessary type promotion in elementwise power

funfact/loss.py
Loss function that doesn't take into account the global phase of the unitary.
```py
ut, _ = np.linalg.qr(np.random.randn(4, 4) + 1j * np.random.randn(4, 4))
eps = 1e-4
um, _ = np.linalg.qr(ut + eps * (np.random.randn(4, 4) + 1j * np.random.randn(4, 4)))
ut = ab.tensor(ut)
um = ab.tensor(um)
umm = ab.stack([np.exp(1j * np.random.randn()) * um for i in range(5)], dim=2)
ff.loss.mse(um, ut)  # this is small
ff.loss.mse(umm, ut, vectorized_along_last=True, sum_vec=False) # these are big
gp_mse = ff.loss.GlobalPhaseMSE()
gp_mse(umm, ut, vectorized_along_last=True, sum_vec=False) # these are small
```
=> matrix MSE loss agnostic to global phase
