funfact/lang/_semiring.py, funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/_latex.py
Minplus, logsumexp and viterbi semiring operations. Closes #13.
=> library of semiring operations, closes #13

funfact/lang/test_ast.py, requirements-devel.txt
=> unit test for the AST module

CHANGELOG.md, funfact/__init__.py, funfact/lang/__init__.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/__init__.py, funfact/lang/interpreter/_shape.py, funfact/lang/interpreter/_vectorize.py, funfact/model/_factorization.py
Draft pull request working towards #14. 
The main outstanding issue is that the vectorizing index is not necessarily the last index after an Einstein operation.
=> multi replica

funfact/model/_factorization.py, funfact/model/test_factorization.py
=> Ellipsis indexing for factorization models + basic bounds checking

funfact/loss.py
Class for loss functions.
Part of #54, #55 and required for #70.
=> Loss class

funfact/optim.py
=> Optimizer class: Adam and RMSprop

funfact/backend/_torch.py, funfact/model/_factorization.py
Small PR to make the factorization model iterable as required for autograd in torch
=> iterable factorization model for torch

docs/api/factorization.md, docs/api/factorize.md, funfact/algorithm.py, funfact/backend/_jax.py, funfact/lang/interpreter/__init__.py, funfact/lang/interpreter/_base.py, funfact/model/_factorization.py, mkdocs.yml
The 'biggest' change here is the creation of the `from_tsrex` method. Everything else is just docs.
=> Refactor and docs for the `factorize` method and `Factorization` class.

funfact/algorithm.py, funfact/backend/_jax.py, funfact/model/_factorization.py, funfact/vectorization.py
> Yu-Hang  1 hour ago
> I am thinking about making the Factorization class agnostic of vectorization. This should remove many complications surround what if nvec=1.
> 
> Yu-Hang  1 hour ago
> The factorize method will carry out vectorization regardless, though.
> 
> Yu-Hang  1 hour ago
> However, vectorization will not be done at the initialization of a Factorization object. It will be done by a pair of standalone vectorize/view/devectorize methods, kind of like what JAX does.
> 
> Daan Camps  43 minutes ago
> That sounds like a neat idea. Probably the vectorize and view methods are sufficient? A devectorize is not really required if we have a view
>
=> Separated the vectorization mechanism from the Factorization class

funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/test_einop.py
=> [BUGFIX] for einop spec strings

funfact/lang/_ast.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_shape.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_vectorize.py
```
a = ff.tensor('a', 2, 3)
b = ff.tensor('b', 3, 4)
c = ff.tensor('c', 2, 4)
fac = ff.Factorization.from_tsrex(a @ b + c)
print(fac())
print(fac.tsrex.asciitree)
```
Output:
```
[[ 4.0013714  -1.4467709  -2.4036796   1.989367  ]
[-1.8094193   0.03287569 -0.20849198  0.86263585]]
binary: add 
├── matmul:  
│   ├── tensor: a 
│   ╰── tensor: b 
╰── tensor: c 
```
=> Matmul using `@`.

funfact/__init__.py, funfact/lang/__init__.py, funfact/lang/_ast.py, funfact/lang/_predefined_literal.py, funfact/lang/_tsrex.py, funfact/lang/interpreter/_ascii.py, funfact/lang/interpreter/_base.py, funfact/lang/interpreter/_einspec.py, funfact/lang/interpreter/_elementwise.py, funfact/lang/interpreter/_evaluation.py, funfact/lang/interpreter/_index_propagation.py, funfact/lang/interpreter/_initialization.py, funfact/lang/interpreter/_latex.py, funfact/lang/interpreter/_shape.py, funfact/lang/interpreter/_slicing_propagation.py, funfact/lang/interpreter/_syntax_validation.py, funfact/lang/interpreter/_vectorize.py
```
a = ff.tensor('a', 2, 3)
b = ff.tensor('b', 3, 1)
c = ff.tensor('c', 4, 3)
fac = ff.Factorization.from_tsrex(a & b & c)
print(fac().shape)
print(fac.tsrex.asciitree)
```
Output:
```
(24, 9)
kron:  
├── kron:  
│   ├── tensor: a 
│   ╰── tensor: b 
╰── tensor: c 
```
=> Indexless Kronecker product using the `&` operator.

funfact/lang/interpreter/_vectorize.py
=> Vectorization of `kron` and `matmul` nodes.

funfact/lang/interpreter/_einop.py, funfact/lang/interpreter/test_einop.py
Also identified and fixed a few bugs in the process.
=> More systematic tests of einop.

docs/pages/user-guide/tsrex.md
Closes #113 by providing exhaustive documentation on ways to create tensor expression.
=> Tensor expression user guide documentation

funfact/lang/interpreter/_einop.py
=> Simple simplifications to `einop`

docs/pages/user-guide/eval.md, docs/pages/user-guide/tsrex.md
=> User guide about evaluation of factorization models

setup.py
Eliminated packages no longer used by the package and lowered version requirements for non-critical dependencies.
=> Reduce dependency version requirements. Fixes #152.

funfact/initializers.py
Currently, `initializers.stack` assumes the underlying object is always a callable. This is inconsistent with our tsrex semantics, which allows initializer classes to be directly supplied (and we will instantiate the classes when necessary). This is now fixed by using a `StackedInitializer` class instead of the thinner wrapper function solution.
=> Fix `initializers.stack` bug when classes are given as the initializer of tensors

docs/api/conditions.md, docs/api/loss.md, docs/api/optim.md, docs/pages/user-guide/factorize.md, funfact/conditions.py, funfact/loss.py, funfact/optim.py, mkdocs.yml
Additions to API reference.
User guide on `factorize`.
Closes #115.
=> user guide for factorize and API reference

docs/pages/user-guide/factorize.md, funfact/algorithm.py, funfact/loss.py, funfact/test_loss.py
In addition to tests, I also relocated the `reduction` argument of the loss functions from `__call__` to `__init__`. `ff.factorize` was also updated to accept either class-valued or object-valued loss arguments.
=> Unit tests for losses.

docs/pages/user-guide/factorize.md, funfact/algorithm.py, funfact/backend/_jax.py, funfact/backend/_numpy.py, funfact/backend/_torch.py, funfact/test_algorithm.py, setup.py, tox.ini
Along with some minor refactorizing of the code.
=> Unit tests for `algorithm.py::factorize`

funfact/model/_factorization.py
Small addition to check the number of factors, useful for generating plots in the quantum notebook.
=> Add __len__ to NodeView

funfact/optim.py, funfact/test_optim.py
=> optim unit tests

funfact/optim.py, funfact/test_optim.py
Added a convergence test for the optimizers.
=> convergence test optim + bugfix RMSprop

funfact/lang/interpreter/_slicing_propagation.py, funfact/model/_factorization.py
In addition, use tuple type for slices consistently in the slice propagator.
=> Support tuple indexing in element/partial acess of the Factorization model

.github/workflows/ci.yml
Actions now trigger on the following conditions:
1. Push events for `master` and `develop`.
2. PRs
3. New tags.
=> Tweak GH actions trigger conditions

docs/pages/user-guide/backends.md
Closes #116.
Still needs more explanation on changing the GPU etc once that is implemented.
=> User guide on backends

docs/pages/user-guide/tsrex.md, funfact/__init__.py, funfact/lang/test_semiring.py
=> update semiring doc and test

funfact/backend/_proxy.py, funfact/backend/_torch.py, funfact/backend/test_proxy.py, funfact/conditions.py, funfact/lang/_semiring.py, funfact/lang/interpreter/_latex.py
ReLU, CeLU, Sigmoid, and replaced our own implementation of log-add-exp with that from the backends.
=> Several ML math functions.

funfact/lang/interpreter/_type_deduction.py, funfact/lang/interpreter/test_type_deduction.py
Fixed an inconsistency between indexed and indexless broadcasting rules.
=> Unify indexed/indexless elementwise broadcasting rules.

docs/pages/user-guide/tsrex.md
=> Update user guide

funfact/lang/interpreter/_einop_compiler.py, funfact/lang/interpreter/_evaluation.py
=> bugfix #217 Tensor transposition

funfact/lang/interpreter/_vectorize.py
If an abstract tensor shows up multiple times in a tensor expression, it should be only vectorized once. Otherwise, each time the `vectorize()` method will create a new abstract tensor object with a different UUID. This will cause the tensor to show up as multiple independent ones in a vectorized equation. A simple lookup table can fix this.
=> Avoid repetitive vectorization of the same abstract tensor. Fixes #228.

funfact/__init__.py, funfact/algorithm.py, funfact/gradient_descent/__init__.py, funfact/gradient_descent/_base.py, funfact/gradient_descent/_driver.py, funfact/gradient_descent/_plugins.py
Uses a driver+plugin pattern to simplify the insertion of user-defined actions to the factorization process. These custom actions/plugins can be used for monitoring/debugging/logging purposes.
Can be used to implement #225.
=> Redesign of the gradient descent loop
